import JSZip from 'jszip'
import type { ScanResult } from '@/lib/framework/types'

export async function generateReportZip(scan: ScanResult): Promise<ArrayBuffer> {
  const zip = new JSZip()

  zip.file('llms.txt', generateLlmsTxt(scan))
  zip.file('robots.txt', generateRobotsTxt(scan))
  zip.file('sitemap.xml', generateSitemapXml(scan))
  zip.file('schema-install.html', generateSchemaHtml(scan))
  zip.file('og-and-canonical.html', generateOgHtml(scan))
  zip.file('faq-schema.html', generateFaqSchemaHtml(scan))
  zip.file('review-schema.html', generateReviewSchemaHtml(scan))
  zip.file('recommendations.md', generateRecommendationsMd(scan))
  zip.file('report.html', generateReportHtml(scan))
  zip.file('README.txt', generateReadme(scan))

  const buffer = await zip.generateAsync({ type: 'arraybuffer', compression: 'DEFLATE' })
  return buffer
}

export function generateLlmsTxt(scan: ScanResult): string {
  return scan.generatedLlmsTxt
}

export function generateRobotsTxt(scan: ScanResult): string {
  const domain = scan.businessInfo.domain || scan.url
  const baseUrl = domain.startsWith('http') ? domain : `https://${domain}`
  return `# robots.txt — generated by Queldrex AI Visibility Scanner for ${domain}
# Upload this file to your website root so it's accessible at ${baseUrl}/robots.txt
# After uploading, rescan at queldrex.com/scanner to confirm the Crawler Access signal passes

User-agent: *
Allow: /

# ── AI Assistants (explicitly permitted) ──────────────────────────────────────
User-agent: GPTBot
Allow: /

User-agent: OAI-SearchBot
Allow: /

User-agent: ChatGPT-User
Allow: /

User-agent: ClaudeBot
Allow: /

User-agent: anthropic-ai
Allow: /

User-agent: PerplexityBot
Allow: /

User-agent: Googlebot
Allow: /

User-agent: Google-Extended
Allow: /

User-agent: Bingbot
Allow: /

# ── Sitemap reference ─────────────────────────────────────────────────────────
Sitemap: ${baseUrl}/sitemap.xml
`
}

export function generateSitemapXml(scan: ScanResult): string {
  const domain = scan.businessInfo.domain || scan.url
  const baseUrl = domain.startsWith('http') ? domain : `https://${domain}`
  const today = new Date().toISOString().split('T')[0]
  const pages = scan.businessInfo.pages?.length
    ? scan.businessInfo.pages.slice(0, 20)
    : [baseUrl]

  const urls = Array.from(new Set([baseUrl, ...pages]))
    .map((page, i) => `  <url>
    <loc>${page.startsWith('http') ? page : `${baseUrl}${page}`}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${i === 0 ? 'weekly' : 'monthly'}</changefreq>
    <priority>${i === 0 ? '1.0' : '0.8'}</priority>
  </url>`)
    .join('\n')

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- sitemap.xml — generated by Queldrex AI Visibility Scanner for ${domain} -->
<!-- Upload this file to your website root so it's accessible at ${baseUrl}/sitemap.xml -->
<!-- Add additional pages following the same pattern below -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`
}

export function generateSchemaHtml(scan: ScanResult): string {
  return `<!-- schema-install.html — generated by Queldrex AI Visibility Scanner -->
<!-- INSTRUCTIONS: Copy the <script> block below and paste it into the <head> of every page -->
<!-- WordPress: Yoast SEO > Schema, or use "Insert Headers and Footers" plugin -->
<!-- Shopify: Online Store > Themes > Edit Code > theme.liquid — paste before </head> -->
<!-- Webflow: Site Settings > Custom Code > Head Code -->
<!-- HTML sites: paste directly inside your <head> tag -->

<script type="application/ld+json">
${scan.generatedJsonLd}
</script>
`
}

export function generateOgHtml(scan: ScanResult): string {
  const b = scan.businessInfo
  const url = b.url || (b.domain ? `https://${b.domain}` : '')
  const name = b.name || b.domain || ''
  const desc = b.description || b.title || `${name} — official website`
  const image = b.image || ''

  return `<!-- og-and-canonical.html — generated by Queldrex AI Visibility Scanner -->
<!-- INSTRUCTIONS: Copy ALL tags below into the <head> section of every page on your site -->
<!-- WordPress: Yoast SEO > Social handles og: tags automatically after you configure it -->
<!--            OR use "Insert Headers and Footers" plugin to add them globally -->
<!-- Shopify: Online Store > Themes > Edit Code > theme.liquid — paste before </head> -->
<!-- Webflow/Squarespace: Site Settings > Custom Code > Head Code -->
<!-- HTML sites: paste directly inside your <head> tag -->

<!-- ── Canonical URL (fixes "Canonical URL" signal) ──────────────────────────── -->
<link rel="canonical" href="${url}">

<!-- ── Open Graph / AI Metadata (fixes "AI Metadata" signal) ─────────────────── -->
<meta property="og:title" content="${name}">
<meta property="og:description" content="${desc}">
<meta property="og:url" content="${url}">
<meta property="og:type" content="website">
<meta property="og:site_name" content="${name}">
${image ? `<meta property="og:image" content="${image}">` : '<!-- og:image — add your logo or hero image URL here: -->'}
<!-- <meta property="og:image" content="${url}/og-image.jpg"> -->

<!-- ── Twitter / X Card ──────────────────────────────────────────────────────── -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="${name}">
<meta name="twitter:description" content="${desc}">
${image ? `<meta name="twitter:image" content="${image}">` : '<!-- <meta name="twitter:image" content="${url}/og-image.jpg"> -->'}

<!-- ── Meta Description (helps AI and search understand your page) ────────────── -->
<meta name="description" content="${desc}">
`
}

export function generateFaqSchemaHtml(scan: ScanResult): string {
  const b = scan.businessInfo
  const name = b.name || b.domain || 'our business'
  const url = b.url || (b.domain ? `https://${b.domain}` : '')
  const today = new Date().toISOString().split('T')[0]

  const schema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    dateModified: today,
    mainEntity: [
      {
        '@type': 'Question',
        name: `What does ${name} do?`,
        acceptedAnswer: { '@type': 'Answer', text: b.description || `${name} provides professional services. Visit ${url} for more information.` },
      },
      {
        '@type': 'Question',
        name: `How do I contact ${name}?`,
        acceptedAnswer: { '@type': 'Answer', text: [b.phone && `Call us at ${b.phone}.`, b.email && `Email us at ${b.email}.`, `Visit ${url}.`].filter(Boolean).join(' ') || `Visit ${url} for contact information.` },
      },
      {
        '@type': 'Question',
        name: `Where is ${name} located?`,
        acceptedAnswer: { '@type': 'Answer', text: b.address || `Visit ${url} for location and hours.` },
      },
    ],
  }

  return `<!-- faq-schema.html — generated by Queldrex AI Visibility Scanner -->
<!-- FIXES: "FAQ Schema" advanced signal — increases Google AI Overviews citation likelihood -->
<!--                                                                                          -->
<!-- INSTRUCTIONS:                                                                            -->
<!--   1. Edit the questions and answers below to match your REAL FAQ content                 -->
<!--   2. Add as many question/answer pairs as you have (remove the { ... } blocks you skip)  -->
<!--   3. Copy the entire <script> block and paste it into your <head>                        -->
<!--   4. WordPress: Install "Insert Headers and Footers" plugin, paste into Header section   -->
<!--   5. Shopify: Online Store > Themes > Edit Code > theme.liquid, paste before </head>     -->
<!--   6. Webflow/Squarespace: Site Settings > Custom Code > Head Code                       -->
<!--                                                                                          -->
<!-- IMPORTANT: Replace all placeholder text in [BRACKETS] with your real content.           -->
<!-- The more specific and helpful your answers, the more likely AI will cite you.            -->

<script type="application/ld+json">
${JSON.stringify(schema, null, 2)}
</script>

<!-- ─────────────────────────────────────────────────────────────────────────── -->
<!-- ADDITIONAL FAQ QUESTIONS — copy this block and add more Q&A pairs          -->
<!-- ─────────────────────────────────────────────────────────────────────────── -->
<!--
{
  "@type": "Question",
  "name": "[What are your hours?]",
  "acceptedAnswer": {
    "@type": "Answer",
    "text": "[We are open Monday–Friday 9am–5pm, Saturday 10am–3pm.]"
  }
},
{
  "@type": "Question",
  "name": "[What makes you different from competitors?]",
  "acceptedAnswer": {
    "@type": "Answer",
    "text": "[Replace with your unique value proposition — be specific and honest.]"
  }
}
-->
`
}

export function generateReviewSchemaHtml(scan: ScanResult): string {
  const b = scan.businessInfo
  const name = b.name || b.domain || 'our business'
  const url = b.url || (b.domain ? `https://${b.domain}` : '')
  const today = new Date().toISOString().split('T')[0]

  const schema = {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    '@id': `${url}/#business`,
    name,
    url,
    dateModified: today,
    aggregateRating: {
      '@type': 'AggregateRating',
      ratingValue: '[YOUR AVERAGE RATING — e.g. 4.9]',
      bestRating: '5',
      worstRating: '1',
      reviewCount: '[YOUR TOTAL REVIEW COUNT — e.g. 127]',
      ratingExplanation: 'Based on verified customer reviews',
    },
    review: [
      {
        '@type': 'Review',
        datePublished: today,
        reviewRating: { '@type': 'Rating', ratingValue: '5', bestRating: '5' },
        author: { '@type': 'Person', name: '[Reviewer First Name]' },
        reviewBody: '[Paste an actual 5-star review from Google or Yelp here]',
      },
    ],
  }

  return `<!-- review-schema.html — generated by Queldrex AI Visibility Scanner -->
<!-- FIXES: "Review Schema" advanced signal — shows your star rating to AI systems -->
<!--                                                                                 -->
<!-- INSTRUCTIONS:                                                                   -->
<!--   1. REQUIRED: Replace [YOUR AVERAGE RATING] with your real Google/Yelp rating -->
<!--   2. REQUIRED: Replace [YOUR TOTAL REVIEW COUNT] with your real review count    -->
<!--   3. OPTIONAL: Replace the sample review with a real 5-star review text         -->
<!--   4. Copy the entire <script> block and paste it into your homepage <head>      -->
<!--   5. WordPress: "Insert Headers and Footers" plugin → Header section            -->
<!--   6. Shopify: theme.liquid → paste before </head>                               -->
<!--   7. Webflow/Squarespace: Site Settings > Custom Code > Head                   -->
<!--                                                                                 -->
<!-- WHERE TO FIND YOUR NUMBERS:                                                     -->
<!--   Google Business Profile: google.com/business → your listing → see the rating -->
<!--   Yelp: your Yelp page → count the stars and total review number               -->
<!--                                                                                 -->
<!-- LEGAL NOTE: Only use your REAL, verified review data. Do not fabricate ratings. -->

<script type="application/ld+json">
${JSON.stringify(schema, null, 2)}
</script>
`
}

function generateReadme(scan: ScanResult): string {
  const domain = scan.businessInfo.domain || scan.url
  const baseUrl = domain.startsWith('http') ? domain : `https://${domain}`
  return `AI VISIBILITY REPORT — ${scan.businessInfo.name}
Generated by Queldrex AI Visibility Scanner — queldrex.com
Date: ${new Date().toLocaleDateString()}    Score: ${scan.score}/100

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ALL 14 AI VISIBILITY SIGNALS — WHAT'S IN THIS PACKAGE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

CORE SIGNALS (scored — fixed by files in this package)
──────────────────────────────────────────────────────
✓ llms.txt              → 25 pts — file included, upload to web root
✓ LocalBusiness Schema  → 20 pts — in schema-install.html, paste to <head>
✓ JSON-LD               → 15 pts — in schema-install.html (same file)
✓ Sitemap               → 10 pts — sitemap.xml included, upload to web root
✓ AI Metadata (OG)      → 10 pts — in og-and-canonical.html, paste to <head>
✓ Canonical URL         → 5 pts  — in og-and-canonical.html (same file)
✓ Crawler Access        → 5 pts  — robots.txt included, upload to web root
✗ HTTPS                 → 10 pts — see HTTPS SETUP section below (no file needed)
                                    Total scorable: up to 90 pts from files alone

ADVANCED SIGNALS (bonus — improve AI citation likelihood)
──────────────────────────────────────────────────────────
✓ Content Freshness     → dateModified added to your schema automatically
✓ FAQ Schema            → faq-schema.html included — fill in YOUR questions & paste
✓ Review Schema         → review-schema.html included — fill in YOUR rating & paste
✗ About / Team page     → see ABOUT PAGE section below (requires creating a page)
✗ Contact page          → see CONTACT PAGE section below (requires creating a page)
✗ JS Rendering          → see JS RENDERING section below (may not apply to you)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FILES IN THIS PACKAGE (10 files)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
report.html           Open in your browser — full score breakdown
recommendations.md    Step-by-step fix checklist (high → medium → low)
llms.txt              UPLOAD to ${baseUrl}/llms.txt
robots.txt            UPLOAD to ${baseUrl}/robots.txt
sitemap.xml           UPLOAD to ${baseUrl}/sitemap.xml (edit first — add your pages)
schema-install.html   PASTE <script> block into every page <head>
og-and-canonical.html PASTE all <meta> and <link> tags into every page <head>
faq-schema.html       EDIT with your real Q&A, then PASTE into homepage <head>
review-schema.html    EDIT with your real rating, then PASTE into homepage <head>
README.txt            This file

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
STEP-BY-STEP INSTALLATION (~20 minutes)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

STEP 1 — Upload 3 files to your web root
  Upload llms.txt, robots.txt, and sitemap.xml to the ROOT folder of your
  website (the same folder that contains your homepage / index.html / index.php).

  Before uploading sitemap.xml: open it in a text editor and add your other
  page URLs following the pattern already in the file.

  Verify each file is live:
    ${baseUrl}/llms.txt      ← should show plain text content
    ${baseUrl}/robots.txt    ← should show plain text content
    ${baseUrl}/sitemap.xml   ← should show XML content

STEP 2 — Add JSON-LD schema to your <head>
  Open schema-install.html in a text editor.
  Copy the entire <script type="application/ld+json"> ... </script> block.
  Paste it into the <head> section of every page on your site.

STEP 3 — Add OG tags + canonical to your <head>
  Open og-and-canonical.html in a text editor.
  Copy ALL of the <meta> and <link rel="canonical"> tags.
  Paste them into the <head> section of every page (same location as step 2).

STEP 4 — Add FAQ Schema (optional but high-value)
  Open faq-schema.html. Replace the placeholder questions/answers with your
  real FAQ content. Copy the <script> block. Paste into your homepage <head>.

STEP 5 — Add Review Schema (optional but high-value)
  Open review-schema.html. Replace [YOUR AVERAGE RATING] and [YOUR TOTAL
  REVIEW COUNT] with your real Google or Yelp numbers. Paste into homepage <head>.

STEP 6 — Rescan
  Go to queldrex.com/scanner and rescan your site.
  Allow 24–48 hours for crawl caches to refresh before rescanning.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
HTTPS SETUP (if your site shows as HTTP)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
HTTPS is worth 10 points and is required for AI crawlers. Most modern hosts
offer free SSL via Let's Encrypt. Steps:

  cPanel hosting:    cPanel → SSL/TLS → Let's Encrypt → Install
  Cloudflare:        SSL/TLS → Overview → Full (strict) → Always Use HTTPS ON
  WordPress.com:     Settings → General → Enable SSL
  Squarespace:       Settings → Security → Enable SSL
  Shopify:           Admin → Online Store → Domains → Enable SSL (automatic)
  Wix:               Settings → Upgrade Plan (SSL requires paid plan)

After enabling SSL, also set up a redirect from http:// to https://.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ABOUT / TEAM PAGE (E-E-A-T signal)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Create a page at ${baseUrl}/about that includes:
  - Your name and credentials / years in business
  - A photo of you or your team
  - Your license numbers or certifications (if applicable)
  - A brief description of your experience

Then add "founder" markup to your JSON-LD in schema-install.html:
  "founder": { "@type": "Person", "name": "[Your Full Name]", "jobTitle": "[Your Title]" }

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CONTACT PAGE (trust signal for AI and users)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Create a page at ${baseUrl}/contact that includes:
  - Business email address
  - Phone number (if applicable)
  - Physical address or service area
  - Business hours
  - A contact form or clear call-to-action

This signals to AI systems that a real, accountable business is behind the website.
AI assistants weight contact information as a trust signal when deciding what to cite.

Also add your contact info to the JSON-LD in schema-install.html:
  "telephone": "[your phone number]",
  "email": "[your business email]"

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
JS RENDERING (if your site is JavaScript-heavy)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
AI crawlers (GPTBot, ClaudeBot, PerplexityBot) do NOT execute JavaScript.
If your site is built with React (CRA/Vite), Vue, or Angular without SSR,
AI bots see a near-empty page.

Short-term fix: The JSON-LD we've provided in schema-install.html is embedded
directly in HTML — this IS visible to AI crawlers even without JS execution.

Long-term fix: Enable server-side rendering (SSR) or static generation (SSG):
  Next.js:     Built-in SSR/SSG — migrate from CRA to Next.js
  React:       Use react-snap for pre-rendering, or migrate to Next.js
  Vue:         Use Nuxt.js
  Angular:     Use Angular Universal

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PLATFORM-SPECIFIC FILE UPLOAD NOTES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
WordPress     cPanel File Manager → public_html/ → upload files
              OR FTP: connect to your host, upload to /public_html/ root

Shopify       Files: use the Shopify Files API or a "File Hosting" app
              robots.txt: Admin → Online Store → Preferences → robots.txt editor
              sitemap.xml: auto-generated at yourstore.myshopify.com/sitemap.xml

Webflow       Hosting > Custom Files OR host on a CDN and point your domain
              For robots.txt: Project Settings > SEO > robots.txt editor

Squarespace   Settings > Advanced > Code Injection for <head> code
              For file uploads: Pages > Not Linked page → use as /llms.txt proxy
              OR contact Squarespace support for root file access

Wix           SEO Tools > robots.txt editor (for robots.txt only)
              For llms.txt: use Wix's Media Manager or contact hello@queldrex.com

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Questions? hello@queldrex.com — we respond within 24 hours
Rescan after install: queldrex.com/scanner`
}

export function generateRecommendationsMd(scan: ScanResult): string {
  const lines: string[] = []
  lines.push(`# AI Visibility Recommendations`)
  lines.push(`**Site:** ${scan.url}`)
  lines.push(`**Score:** ${scan.score}/100`)
  lines.push(`**Date:** ${new Date().toLocaleDateString()}`)
  lines.push('')

  const high = scan.recommendations.filter(r => r.priority === 'HIGH')
  const medium = scan.recommendations.filter(r => r.priority === 'MEDIUM')
  const low = scan.recommendations.filter(r => r.priority === 'LOW')

  if (high.length > 0) {
    lines.push('## High Priority (Do These First)')
    for (const r of high) {
      lines.push(`### ${r.title}`)
      lines.push(r.description)
      lines.push('')
      lines.push(`**How to fix:** ${r.fix}`)
      lines.push('')
    }
  }

  if (medium.length > 0) {
    lines.push('## Medium Priority')
    for (const r of medium) {
      lines.push(`### ${r.title}`)
      lines.push(r.description)
      lines.push('')
      lines.push(`**How to fix:** ${r.fix}`)
      lines.push('')
    }
  }

  if (low.length > 0) {
    lines.push('## Low Priority')
    for (const r of low) {
      lines.push(`### ${r.title}`)
      lines.push(r.description)
      lines.push('')
      lines.push(`**How to fix:** ${r.fix}`)
      lines.push('')
    }
  }

  return lines.join('\n')
}

export function generateReportHtml(scan: ScanResult): string {
  const checkRow = (label: string, passed: boolean, points: number, note?: string) => `
    <tr>
      <td style="padding:12px 16px;border-bottom:1px solid #f0f0f0;">
        <span>${label}</span>
        ${note ? `<div style="font-size:11px;color:#9ca3af;margin-top:2px;">${note}</div>` : ''}
      </td>
      <td style="padding:12px 16px;border-bottom:1px solid #f0f0f0;text-align:center;">
        ${passed
          ? `<span style="color:#16a34a;font-weight:600;">✓ Found</span>`
          : `<span style="color:#dc2626;font-weight:600;">✗ Missing</span>`}
      </td>
      <td style="padding:12px 16px;border-bottom:1px solid #f0f0f0;text-align:center;">
        ${passed ? `<span style="color:#16a34a;">+${points}</span>` : `<span style="color:#9ca3af;">0</span>`}
      </td>
    </tr>`

  const advancedRow = (label: string, passed: boolean, note: string) => `
    <tr>
      <td style="padding:12px 16px;border-bottom:1px solid #f0f0f0;">
        <span>${label}</span>
        <div style="font-size:11px;color:#9ca3af;margin-top:2px;">${note}</div>
      </td>
      <td style="padding:12px 16px;border-bottom:1px solid #f0f0f0;text-align:center;">
        ${passed
          ? `<span style="color:#16a34a;font-weight:600;">✓ Detected</span>`
          : `<span style="color:#dc2626;font-weight:600;">✗ Not found</span>`}
      </td>
      <td style="padding:12px 16px;border-bottom:1px solid #f0f0f0;text-align:center;">
        <span style="color:#9ca3af;font-size:11px;">bonus</span>
      </td>
    </tr>`

  const scoreColor = scan.score >= 70 ? '#16a34a' : scan.score >= 40 ? '#d97706' : '#dc2626'
  const ext = scan.extendedChecks

  const esc = (s: string) => s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')

  const recsHtml = scan.recommendations
    .map(
      r => `
    <div style="margin-bottom:20px;padding:16px;border-left:4px solid ${r.priority === 'HIGH' ? '#dc2626' : r.priority === 'MEDIUM' ? '#d97706' : '#6b7280'};background:#fafafa;border-radius:0 8px 8px 0;">
      <div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.05em;color:${r.priority === 'HIGH' ? '#dc2626' : r.priority === 'MEDIUM' ? '#d97706' : '#6b7280'};margin-bottom:6px;">${r.priority}</div>
      <div style="font-weight:600;font-size:15px;margin-bottom:8px;">${esc(r.title)}</div>
      <div style="color:#374151;margin-bottom:10px;line-height:1.6;">${esc(r.description)}</div>
      <div style="background:#fff;padding:12px;border-radius:6px;border:1px solid #e5e7eb;font-size:13px;color:#1d4ed8;white-space:pre-wrap;"><strong>Fix:</strong> ${esc(r.fix)}</div>
    </div>`
    )
    .join('')

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AI Visibility Report — ${scan.businessInfo.name}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 0; padding: 0; background: #f8fafc; color: #1e293b; }
    .container { max-width: 760px; margin: 40px auto; padding: 0 20px 60px; }
    .header { background: linear-gradient(135deg, #0f172a 0%, #1e3a5f 100%); color: white; padding: 40px; border-radius: 16px; margin-bottom: 32px; }
    .brand { font-size: 13px; font-weight: 600; letter-spacing: 0.1em; text-transform: uppercase; opacity: 0.7; margin-bottom: 12px; }
    .score-badge { display: inline-block; font-size: 64px; font-weight: 800; color: ${scoreColor}; }
    table { width: 100%; border-collapse: collapse; background: white; border-radius: 12px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.06); margin-bottom: 32px; }
    th { background: #f8fafc; padding: 12px 16px; text-align: left; font-size: 12px; text-transform: uppercase; letter-spacing: 0.05em; color: #6b7280; font-weight: 600; }
    .section-title { font-size: 20px; font-weight: 700; margin: 32px 0 16px; }
    .section-subtitle { font-size: 13px; color: #6b7280; margin: -10px 0 16px; }
    .footer { text-align: center; color: #9ca3af; font-size: 13px; margin-top: 48px; }
  </style>
</head>
<body>
<div class="container">
  <div class="header">
    <div class="brand">Queldrex AI Visibility Scanner</div>
    <h1 style="margin:0 0 8px;font-size:28px;">${scan.businessInfo.name}</h1>
    <div style="opacity:0.7;margin-bottom:24px;">${scan.url}</div>
    <div>
      <div style="font-size:13px;opacity:0.7;margin-bottom:4px;">AI VISIBILITY SCORE</div>
      <div class="score-badge">${scan.score}<span style="font-size:28px;opacity:0.6;">/100</span></div>
    </div>
  </div>

  <div class="section-title">Core Signal Checklist</div>
  <p class="section-subtitle">These 8 signals determine your AI Visibility Score.</p>
  <table>
    <thead><tr>
      <th>Signal</th><th style="text-align:center;">Status</th><th style="text-align:center;">Points</th>
    </tr></thead>
    <tbody>
      ${checkRow('llms.txt', scan.checks.llmsTxt, 25, 'Tells AI assistants exactly what your business does')}
      ${checkRow('LocalBusiness Schema', scan.checks.localBusinessSchema, 20, 'Machine-readable business identity for AI & search')}
      ${checkRow('JSON-LD Structured Data', scan.checks.jsonLd, 15, 'Any structured data detectable by AI crawlers')}
      ${checkRow('sitemap.xml', scan.checks.sitemapXml, 10, 'Helps AI crawlers discover all your pages')}
      ${checkRow('Open Graph / AI Metadata', scan.checks.openGraph, 10, 'og:title, og:description read by AI link previewers')}
      ${checkRow('HTTPS', scan.checks.httpsEnabled, 10, 'AI crawlers skip HTTP-only sites')}
      ${checkRow('Crawler Access (robots.txt)', scan.checks.robotsTxt, 5, 'Controls which bots can read your site')}
      ${checkRow('Canonical Tag', scan.checks.canonicalTag, 5, 'Tells AI which URL is the authoritative version')}
    </tbody>
  </table>

  ${ext ? `
  <div class="section-title">Advanced Analysis</div>
  <p class="section-subtitle">5 bonus signals that increase AI citation likelihood. Not counted in your score.</p>
  <table>
    <thead><tr>
      <th>Signal</th><th style="text-align:center;">Status</th><th style="text-align:center;"></th>
    </tr></thead>
    <tbody>
      ${advancedRow('FAQ Schema', ext.faqSchema, 'Google AI Overviews — FAQPage JSON-LD drives AI snippets')}
      ${advancedRow('Review / Rating Schema', ext.reviewSchema, 'Authority signal — AggregateRating tells AI your star rating')}
      ${advancedRow('About / Team Page', ext.aboutPage, 'E-E-A-T signal — establishes expertise and trustworthiness')}
      ${advancedRow('Content Freshness', ext.contentFresh, 'Recency signal — dateModified within the last 12 months')}
      ${advancedRow('JS Rendering', !ext.jsHeavy, 'Crawlability — site content visible without JavaScript')}
    </tbody>
  </table>` : ''}

  <div class="section-title">Recommendations</div>
  ${recsHtml}

  <div class="footer">
    Generated by Queldrex AI Visibility Scanner · ${new Date().toLocaleDateString()} · queldrex.com
  </div>
</div>
</body>
</html>`
}
