import JSZip from 'jszip'
import type { ScanResult } from '@/lib/framework/types'

export async function generateReportZip(scan: ScanResult): Promise<ArrayBuffer> {
  const zip = new JSZip()

  zip.file('llms.txt', scan.generatedLlmsTxt)

  zip.file(
    'schema-install.html',
    `<!-- INSTALLATION INSTRUCTIONS -->\n<!-- Copy everything between the <script> tags and paste it into the <head> of your website -->\n<!-- In WordPress: use SEOPress or Rank Math > Schema. In Shopify: paste into theme.liquid before </head> -->\n\n<script type="application/ld+json">\n${scan.generatedJsonLd}\n</script>`
  )

  const recsMd = generateRecommendationsMd(scan)
  zip.file('recommendations.md', recsMd)

  const reportHtml = generateReportHtml(scan)
  zip.file('report.html', reportHtml)

  zip.file(
    'README.txt',
    `AI Visibility Report for ${scan.businessInfo.name}
Generated by Queldrex AI Visibility Scanner
Date: ${new Date().toLocaleDateString()}
Score: ${scan.score}/100

FILES IN THIS PACKAGE
─────────────────────────────────────────────
report.html         Open in your browser — full visual report with score breakdown
llms.txt            Upload to your web root at: ${scan.url}/llms.txt
schema-install.html Copy the <script> tag inside into your site <head>
recommendations.md  Step-by-step fix checklist, highest impact first
README.txt          This file

QUICK START
─────────────────────────────────────────────
1. Upload llms.txt to your hosting root (same folder as your homepage)
2. Open schema-install.html, copy the <script type="application/ld+json"> block
3. Paste it into the <head> section of every page (or use Yoast/Rank Math in WordPress)
4. Rescan your site at queldrex.com/scanner to verify your new score

Questions? hello@queldrex.com`
  )

  const buffer = await zip.generateAsync({ type: 'arraybuffer', compression: 'DEFLATE' })
  return buffer
}

function generateRecommendationsMd(scan: ScanResult): string {
  const lines: string[] = []
  lines.push(`# AI Visibility Recommendations`)
  lines.push(`**Site:** ${scan.url}`)
  lines.push(`**Score:** ${scan.score}/100`)
  lines.push(`**Date:** ${new Date().toLocaleDateString()}`)
  lines.push('')

  const high = scan.recommendations.filter(r => r.priority === 'HIGH')
  const medium = scan.recommendations.filter(r => r.priority === 'MEDIUM')
  const low = scan.recommendations.filter(r => r.priority === 'LOW')

  if (high.length > 0) {
    lines.push('## High Priority (Do These First)')
    for (const r of high) {
      lines.push(`### ${r.title}`)
      lines.push(r.description)
      lines.push('')
      lines.push(`**How to fix:** ${r.fix}`)
      lines.push('')
    }
  }

  if (medium.length > 0) {
    lines.push('## Medium Priority')
    for (const r of medium) {
      lines.push(`### ${r.title}`)
      lines.push(r.description)
      lines.push('')
      lines.push(`**How to fix:** ${r.fix}`)
      lines.push('')
    }
  }

  if (low.length > 0) {
    lines.push('## Low Priority')
    for (const r of low) {
      lines.push(`### ${r.title}`)
      lines.push(r.description)
      lines.push('')
      lines.push(`**How to fix:** ${r.fix}`)
      lines.push('')
    }
  }

  return lines.join('\n')
}

function generateReportHtml(scan: ScanResult): string {
  const checkRow = (label: string, passed: boolean, points: number, note?: string) => `
    <tr>
      <td style="padding:12px 16px;border-bottom:1px solid #f0f0f0;">
        <span>${label}</span>
        ${note ? `<div style="font-size:11px;color:#9ca3af;margin-top:2px;">${note}</div>` : ''}
      </td>
      <td style="padding:12px 16px;border-bottom:1px solid #f0f0f0;text-align:center;">
        ${passed
          ? `<span style="color:#16a34a;font-weight:600;">✓ Found</span>`
          : `<span style="color:#dc2626;font-weight:600;">✗ Missing</span>`}
      </td>
      <td style="padding:12px 16px;border-bottom:1px solid #f0f0f0;text-align:center;">
        ${passed ? `<span style="color:#16a34a;">+${points}</span>` : `<span style="color:#9ca3af;">0</span>`}
      </td>
    </tr>`

  const advancedRow = (label: string, passed: boolean, note: string) => `
    <tr>
      <td style="padding:12px 16px;border-bottom:1px solid #f0f0f0;">
        <span>${label}</span>
        <div style="font-size:11px;color:#9ca3af;margin-top:2px;">${note}</div>
      </td>
      <td style="padding:12px 16px;border-bottom:1px solid #f0f0f0;text-align:center;">
        ${passed
          ? `<span style="color:#16a34a;font-weight:600;">✓ Detected</span>`
          : `<span style="color:#dc2626;font-weight:600;">✗ Not found</span>`}
      </td>
      <td style="padding:12px 16px;border-bottom:1px solid #f0f0f0;text-align:center;">
        <span style="color:#9ca3af;font-size:11px;">bonus</span>
      </td>
    </tr>`

  const scoreColor = scan.score >= 70 ? '#16a34a' : scan.score >= 40 ? '#d97706' : '#dc2626'
  const ext = scan.extendedChecks

  const recsHtml = scan.recommendations
    .map(
      r => `
    <div style="margin-bottom:20px;padding:16px;border-left:4px solid ${r.priority === 'HIGH' ? '#dc2626' : r.priority === 'MEDIUM' ? '#d97706' : '#6b7280'};background:#fafafa;border-radius:0 8px 8px 0;">
      <div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.05em;color:${r.priority === 'HIGH' ? '#dc2626' : r.priority === 'MEDIUM' ? '#d97706' : '#6b7280'};margin-bottom:6px;">${r.priority}</div>
      <div style="font-weight:600;font-size:15px;margin-bottom:8px;">${r.title}</div>
      <div style="color:#374151;margin-bottom:10px;line-height:1.6;">${r.description}</div>
      <div style="background:#fff;padding:12px;border-radius:6px;border:1px solid #e5e7eb;font-size:13px;color:#1d4ed8;white-space:pre-wrap;"><strong>Fix:</strong> ${r.fix}</div>
    </div>`
    )
    .join('')

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AI Visibility Report — ${scan.businessInfo.name}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 0; padding: 0; background: #f8fafc; color: #1e293b; }
    .container { max-width: 760px; margin: 40px auto; padding: 0 20px 60px; }
    .header { background: linear-gradient(135deg, #0f172a 0%, #1e3a5f 100%); color: white; padding: 40px; border-radius: 16px; margin-bottom: 32px; }
    .brand { font-size: 13px; font-weight: 600; letter-spacing: 0.1em; text-transform: uppercase; opacity: 0.7; margin-bottom: 12px; }
    .score-badge { display: inline-block; font-size: 64px; font-weight: 800; color: ${scoreColor}; }
    table { width: 100%; border-collapse: collapse; background: white; border-radius: 12px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.06); margin-bottom: 32px; }
    th { background: #f8fafc; padding: 12px 16px; text-align: left; font-size: 12px; text-transform: uppercase; letter-spacing: 0.05em; color: #6b7280; font-weight: 600; }
    .section-title { font-size: 20px; font-weight: 700; margin: 32px 0 16px; }
    .section-subtitle { font-size: 13px; color: #6b7280; margin: -10px 0 16px; }
    .footer { text-align: center; color: #9ca3af; font-size: 13px; margin-top: 48px; }
  </style>
</head>
<body>
<div class="container">
  <div class="header">
    <div class="brand">Queldrex AI Visibility Scanner</div>
    <h1 style="margin:0 0 8px;font-size:28px;">${scan.businessInfo.name}</h1>
    <div style="opacity:0.7;margin-bottom:24px;">${scan.url}</div>
    <div>
      <div style="font-size:13px;opacity:0.7;margin-bottom:4px;">AI VISIBILITY SCORE</div>
      <div class="score-badge">${scan.score}<span style="font-size:28px;opacity:0.6;">/100</span></div>
    </div>
  </div>

  <div class="section-title">Core Signal Checklist</div>
  <p class="section-subtitle">These 8 signals determine your AI Visibility Score.</p>
  <table>
    <thead><tr>
      <th>Signal</th><th style="text-align:center;">Status</th><th style="text-align:center;">Points</th>
    </tr></thead>
    <tbody>
      ${checkRow('llms.txt', scan.checks.llmsTxt, 25, 'Tells AI assistants exactly what your business does')}
      ${checkRow('LocalBusiness Schema', scan.checks.localBusinessSchema, 20, 'Machine-readable business identity for AI & search')}
      ${checkRow('JSON-LD Structured Data', scan.checks.jsonLd, 15, 'Any structured data detectable by AI crawlers')}
      ${checkRow('sitemap.xml', scan.checks.sitemapXml, 10, 'Helps AI crawlers discover all your pages')}
      ${checkRow('Open Graph / AI Metadata', scan.checks.openGraph, 10, 'og:title, og:description read by AI link previewers')}
      ${checkRow('HTTPS', scan.checks.httpsEnabled, 10, 'AI crawlers skip HTTP-only sites')}
      ${checkRow('Crawler Access (robots.txt)', scan.checks.robotsTxt, 5, 'Controls which bots can read your site')}
      ${checkRow('Canonical Tag', scan.checks.canonicalTag, 5, 'Tells AI which URL is the authoritative version')}
    </tbody>
  </table>

  ${ext ? `
  <div class="section-title">Advanced Analysis</div>
  <p class="section-subtitle">5 bonus signals that increase AI citation likelihood. Not counted in your score.</p>
  <table>
    <thead><tr>
      <th>Signal</th><th style="text-align:center;">Status</th><th style="text-align:center;"></th>
    </tr></thead>
    <tbody>
      ${advancedRow('FAQ Schema', ext.faqSchema, 'Google AI Overviews — FAQPage JSON-LD drives AI snippets')}
      ${advancedRow('Review / Rating Schema', ext.reviewSchema, 'Authority signal — AggregateRating tells AI your star rating')}
      ${advancedRow('About / Team Page', ext.aboutPage, 'E-E-A-T signal — establishes expertise and trustworthiness')}
      ${advancedRow('Content Freshness', ext.contentFresh, 'Recency signal — dateModified within the last 12 months')}
      ${advancedRow('JS Rendering', !ext.jsHeavy, 'Crawlability — site content visible without JavaScript')}
    </tbody>
  </table>` : ''}

  <div class="section-title">Recommendations</div>
  ${recsHtml}

  <div class="footer">
    Generated by Queldrex AI Visibility Scanner · ${new Date().toLocaleDateString()} · queldrex.com
  </div>
</div>
</body>
</html>`
}
