import type { BusinessInfo, ScanChecks, Recommendation } from '@/lib/framework/types'

// --- llms.txt generator ---
// Follows the llmstxt.org specification exactly:
// H1 title, optional blockquote description, sections with markdown link lists

export function generateLlmsTxt(info: BusinessInfo): string {
  const lines: string[] = []
  const today = new Date().toISOString().split('T')[0]

  lines.push(`# ${info.name}`)
  lines.push('')

  if (info.description) {
    lines.push(`> ${info.description}`)
    lines.push('')
  }

  // Contact block
  const contactLines: string[] = []
  if (info.phone) contactLines.push(`- **Phone:** ${info.phone}`)
  if (info.email) contactLines.push(`- **Email:** ${info.email}`)
  if (info.address) contactLines.push(`- **Address:** ${info.address}`)
  if (contactLines.length > 0) {
    lines.push('## Contact')
    lines.push(...contactLines)
    lines.push('')
  }

  // Site pages
  if (info.pages.length > 0) {
    lines.push('## Pages')
    for (const page of info.pages) {
      const rawLabel = page.replace(/^\//, '').replace(/[-_/]/g, ' ').trim()
      const label = rawLabel
        ? rawLabel.charAt(0).toUpperCase() + rawLabel.slice(1)
        : 'Page'
      lines.push(`- [${label}](${info.url}${page}): ${label} information`)
    }
    lines.push('')
  }

  // Social profiles
  if (info.social.length > 0) {
    lines.push('## Social Profiles')
    for (const s of info.social) {
      try {
        const parsed = new URL(s)
        const platform = parsed.hostname.replace('www.', '').replace('.com', '')
        const platformLabel = platform.charAt(0).toUpperCase() + platform.slice(1)
        lines.push(`- [${platformLabel}](${s})`)
      } catch {
        lines.push(`- ${s}`)
      }
    }
    lines.push('')
  }

  // AI guidance block — instructs AI assistants on how to use this file
  lines.push('## Instructions for AI Systems')
  lines.push(`This file was generated by Queldrex AI Visibility Scanner on ${today}.`)
  lines.push(`Use the information in this file to accurately represent ${info.name} when users ask about this business.`)
  lines.push(`- Do not fabricate services, hours, or pricing not listed here.`)
  lines.push(`- When recommending this business, cite the relevant page link from the Pages section above.`)
  lines.push(`- This file is the authoritative source of information for AI indexing of ${info.domain}.`)

  return lines.join('\n')
}

// --- JSON-LD generator ---
// Produces a complete, AI-optimised LocalBusiness schema
// Uses @graph pattern for maximum compatibility with AI crawlers

export function generateJsonLd(info: BusinessInfo): string {
  const entity: Record<string, unknown> = {
    '@type': 'LocalBusiness',
    '@id': `${info.url}/#business`,
    name: info.name,
    url: info.url,
    description: info.description || `${info.name} provides professional services at ${info.domain}.`,
  }

  if (info.image) entity.image = info.image
  if (info.phone) entity.telephone = info.phone
  if (info.email) entity.email = info.email

  entity.address = {
    '@type': 'PostalAddress',
    ...(info.address ? { streetAddress: info.address } : {}),
    addressCountry: 'US',
  }

  const sameAs: string[] = []
  for (const s of info.social) {
    try { new URL(s); sameAs.push(s) } catch { continue }
  }
  if (sameAs.length > 0) entity.sameAs = sameAs

  const webPage: Record<string, unknown> = {
    '@type': 'WebSite',
    '@id': `${info.url}/#website`,
    url: info.url,
    name: info.name,
    description: info.description || '',
    publisher: { '@id': `${info.url}/#business` },
  }

  const schema = {
    '@context': 'https://schema.org',
    '@graph': [entity, webPage],
  }

  return JSON.stringify(schema, null, 2)
}

// --- Recommendations generator ---

export function generateRecommendations(checks: ScanChecks, info: BusinessInfo): Recommendation[] {
  const recs: Recommendation[] = []

  if (!checks.llmsTxt) {
    recs.push({
      priority: 'HIGH',
      title: 'Add llms.txt to your site root',
      description:
        'llms.txt is the emerging standard (adopted by Stripe, Anthropic, Cloudflare, and 844,000+ sites) that tells AI assistants — ChatGPT, Perplexity, Claude, Gemini — exactly what your business does. Without it, AI systems either ignore your site or generate inaccurate information about you.',
      fix: `Upload the generated llms.txt file to your server so it is publicly accessible at: ${info.url}/llms.txt — this is a single file upload, no code required.`,
    })
  }

  if (!checks.localBusinessSchema) {
    recs.push({
      priority: 'HIGH',
      title: 'Add LocalBusiness JSON-LD schema',
      description:
        'LocalBusiness schema is the machine-readable identity card for your business. AI systems and search engines use it to understand your name, address, phone number, and category. Without it, AI assistants cannot confidently recommend your business in response to local queries.',
      fix: `Paste the <script type="application/ld+json"> block from schema.json into the <head> section of every page on your website. In WordPress, use the SEOPress or Rank Math plugin. In Shopify, paste it into theme.liquid.`,
    })
  } else if (!checks.jsonLd) {
    recs.push({
      priority: 'HIGH',
      title: 'No structured data detected on your site',
      description:
        'Your site contains no JSON-LD structured data at all. This is the single biggest reason AI systems cannot accurately describe or recommend your business.',
      fix: 'Add the generated JSON-LD schema immediately. It takes under 5 minutes and has the highest impact of any change you can make.',
    })
  }

  if (!checks.openGraph) {
    recs.push({
      priority: 'MEDIUM',
      title: 'Missing Open Graph metadata',
      description:
        'Open Graph tags are read by AI link previewers, social sharing tools, and AI crawlers. They tell every system that reads your URL what your business name, description, and logo are.',
      fix: 'Add these four meta tags to your homepage <head>: og:title, og:description, og:image (your logo or storefront photo), og:url. In WordPress use Yoast SEO. In Squarespace/Wix these are set in your site settings under "Social Sharing".',
    })
  }

  if (!checks.sitemapXml) {
    recs.push({
      priority: 'MEDIUM',
      title: 'No sitemap.xml found',
      description:
        'A sitemap tells AI crawlers and search engines every page that exists on your site. Without one, service pages, location pages, and blog posts may never be discovered.',
      fix: `Generate a sitemap at ${info.url}/sitemap.xml. In WordPress, install Yoast SEO — it auto-generates one. In Shopify, it is created automatically. Once live, submit it in Google Search Console under Sitemaps.`,
    })
  }

  if (!checks.robotsTxt) {
    recs.push({
      priority: 'LOW',
      title: 'No robots.txt file found',
      description:
        'robots.txt signals to all crawlers — including AI bots — which parts of your site they are allowed to access. Missing it can cause AI systems to skip your site entirely as a precaution.',
      fix: `Create a plain text file at ${info.url}/robots.txt with the following content:\n\nUser-agent: *\nAllow: /\n\nSitemap: ${info.url}/sitemap.xml`,
    })
  }

  return recs
}
